name: Solar System Workflow

on:
    workflow_dispatch:
    push:
        branches:
            - main
            - 'feature/*'

env:
    MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
    build:
        name: build and test
        runs-on: ubuntu-latest

        steps:
            - name: clone repo
              uses: actions/checkout@v5

            - name: setup node
              uses: actions/setup-node@v5
              with:
                node-version: '18'

            - name: install dependencies
              run: npm install

            - name: test
              run: npm test

            - name: archive test results
              uses: actions/upload-artifact@v5
              with:
                name: mocha-test-results
                path: test-results.xml