name: Solar System Workflow

on:
    workflow_dispatch:
    push:
        branches:
            - main
            - 'feature/*'

env:
    MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
    build:
        name: build and test
        runs-on: ubuntu-latest #${{ matrix.os-version }}

        # strategy:
        #     matrix:
        #         node-version: [18,19,20]
        #         os-version: [ubuntu-latest, windows-latest]
        #         exclude:
        #             - node-version: 18
        #               os-version: macos-latest

        steps:
            - name: clone repo
              uses: actions/checkout@v5

            - name: setup node #${{ matrix.node-version }} on ${{ matrix.os-version }}
              uses: actions/setup-node@v5
              with:
                node-version: '18' #${{ matrix.node-version}}

            - name: cache dependencies
              uses: actions/cache@v4
              with:
                path: node_modules
                key: ${{ runner.os }}-node-modues-${{ hashFiles('package-lock.json') }}

            - name: install dependencies
              run: npm install

            - name: test
              run: npm test

            - name: archive test results
              uses: actions/upload-artifact@v5
              with:
                name: mocha-test-results
                path: test-results.xml
                retention-days: 2

            - name: code coverage
              id: code-coverage
              run: npm run coverage
              continue-on-error: true

            - name: upload code coverage
              uses: actions/upload-artifact@v5
              with:
                name: code-coverage
                path: coverage
                retention-days: 2
              # if: success()
              if: steps.code-coverage.outcome == 'success'


    docker:
        name: build and test docker image
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: clone repo
              uses: actions/checkout@v5

            - name: DockerHub login
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}

            - name: Docker build for testing
              uses: docker/build-push-action@v6
              with:
                context: .
                push: false
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}

            - name: Docker Image Testing
              run: |
                docker images
                docker run --name solar-system-app -d \
                    -p 3000:3000 \
                    -e MONGO_URI=$MONGO_URI \
                    -e MONGO_USERNAME=$MONGO_USERNAME \
                    -e MONGO_PASSWORD=$MONGO_PASSWORD \
                    ${{ secrets.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}

                wget -q -O - 127.0.0.1:3000/live | grep live

            - name: Docker Image Push
              uses: docker/build-push-action@v6
              with:
                context: .
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
                
