name: Solar System Workflow

on:
    workflow_dispatch:
    push:
        branches:
            - main
            - 'feature/*'

env:
    MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
    build:
        name: build and test
        runs-on: ${{ matrix.os-version }}

        strategy:
            matrix:
                node-version: [18,19,20]
                os-version: [ubuntu-latest, windows-latest]
                exclude:
                    - node-version: 18
                      os-version: macos-latest

        steps:
            - name: clone repo
              uses: actions/checkout@v5

            - name: setup node ${{ matrix.node-version }} on ${{ matrix.os-version }}
              uses: actions/setup-node@v5
              with:
                node-version: ${{ matrix.node-version}}

            - name: install dependencies
              run: npm install

            - name: test
              run: npm test

            - name: archive test results
              uses: actions/upload-artifact@v5
              with:
                name: mocha-test-results
                path: test-results.xml
                retention-days: 2

            - name: code coverage
              run: npm run coverage

            - name: upload code coverage
              uses: actions/upload-artifact@v5
              with:
                name: code-coverage
                path: coverage
                retention-days: 2
